//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimatedColorfulMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int billDetailID { get; set; }
        public int billID { get; set; }
        public int productID { get; set; }
        public int numberProduct { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
