//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimatedColorfulMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int payDetailID { get; set; }
        public int payID { get; set; }
        public int resourcesID { get; set; }
        public int numberResources { get; set; }
        public double sumPrice { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
